services:
  app:
    build: .
    ports:
      - "8443:8080" # HTTPS
      - "8080:8080" # HTTP (Redirect or Fallback)
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=card_registry
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ENCRYPTION_KEY=MTIzNDU2Nzg5MDEyMzQ1NjcyM2I0NTY3ODkwMTIzNDU= # Example Key (32 bytes base64)
      - HASH_KEY=MTIzNDU2Nzg5MDEyMzQ1NjcyM2I0NTY3ODkwMTIzNDU= # Example Key
      - TOKEN_ISSUER=hyperativa
      - TOKEN_AUDIENCE=card-api
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      prometheus:
        condition: service_started

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=card_registry
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
